name: Build macOS

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure
