name: Build Windows

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure
